const PATH = {
  HOME: '/home',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  LOGIN: '/login',
  USER: '/user',
  USER_DETAIL: '/user/:userId',
  USER_UPDATE: '/user/:userId/edit',
  USER_PROFILE: '/user/profile',
  TICKET: '/ticket',
  TICKET_DETAIL: '/admin/ticket/:ticketId',
  TICKET_ADD_GAN_MOI: '/admin/ticket/add/ticket-gan-moi',
  TICKET_ADD_NANG_DOI: '/admin/ticket/add/ticket-nang-doi',
  TICKET_ADD_DKDMC: '/admin/ticket/add/ticket-dang-ky-dinh-muc',
  TICKET_ADD_DOC_SO: '/admin/ticket/add/ticket-doc-so',
  TICKET_ADD_STCN: '/admin/ticket/add/ticket-sang-ten-ca-nhan',
  TICKET_ADD_STDN: '/admin/ticket/add/ticket-sang-ten-doanh-nghiep',
  TICKET_ADD_HDDT: '/admin/ticket/add/ticket-hop-dong-dien-tu',
  TICKET_ADD_SU_CO: '/admin/ticket/add/ticket-su-co',
  ADMIN_ROLE_ROLES: '/admin/roles',
  ADMIN_ROLE_PERMISSIONS: '/admin/permissions',
  ADMIN_ROLE_ROLES_ID: '/admin/roles/:id',
  ADMIN_ROLE_ROLES_ID_EDIT: '/admin/roles/:id/edit',
  ADMIN_ROLE_ASSIGN_PERMISSION: '/admin/assign-permission',
  ADMIN_ROLE_ASSIGN_ROLE: '/admin/assign-role',
  MESSAGE: '/admin/message',
  MESSAGE_DETAIL: '/admin/message/:id',
  CHATBOT: '/chatbot',
  WATER_QUALITY: '/water-quality',
} as const

export default PATH
